import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { Word, Level, LEVEL_INFO, CATEGORY_INFO, Category } from '../types';

// ==========================================
// Font Loading Helper
// ==========================================
// Noto Sans KR (Regular) - Public URL or hosted asset

async function loadKoreanFont(doc: jsPDF) {
    try {
        // Using a reliable source for a Korean TTF file.

        // Let's try to use the system font if possible? No, PDF needs embedded font.
        // We will use a fallback approach: 
        // If we can't easily fetch a font, we might need the user to provide one. 
        // But to be helpful, let's try a standard one.

        // Using a reliable source for a Korean TTF file.
        // NanumGothic is often used.
        const fontUrl = 'https://cdn.jsdelivr.net/gh/googlefonts/noto-fonts@main/hinted/ttf/NotoSansKR/NotoSansKR-Regular.ttf';

        // Optimization: Check if font is already added? jsPDF doesn't have a simple check API, but we can manage a global flag if needed.
        // For now, let's fetch.
        const res = await fetch(fontUrl);
        if (!res.ok) throw new Error('Failed to load font');
        const buffer = await res.arrayBuffer();

        // Convert to Uint8Array
        const fontData = new Uint8Array(buffer);

        // Add to VFS
        doc.addFileToVFS('NotoSansKR-Regular.ttf', fontData as any); // Cast to any to avoid type issues with VFS
        doc.addFont('NotoSansKR-Regular.ttf', 'NotoSansKR', 'normal');
        doc.setFont('NotoSansKR');

        return true;
    } catch (error) {
        console.error('Font loading failed:', error);
        return false;
    }
}

// ==========================================
// PDF Generation Functions
// ==========================================

export async function generateDayVocaPDF(
    level: Level,
    day: number,
    words: Word[],
    category?: Category | null
) {
    const doc = new jsPDF();

    // 1. Load Font
    const fontLoaded = await loadKoreanFont(doc);
    if (!fontLoaded) {
        alert('한글 폰트 로드에 실패했습니다. PDF에 한글이 깨질 수 있습니다.');
    }

    const levelName = LEVEL_INFO[level].nameKo;
    const title = category
        ? `${levelName} - ${CATEGORY_INFO[category].nameKo}`
        : `${levelName} - Day ${day}`;

    // 2. Header
    doc.setFontSize(18);
    doc.text(title, 14, 20); // x, y (mm)

    doc.setFontSize(10);
    doc.text(`Generated by VocaMaster30 | ${new Date().toLocaleDateString()}`, 14, 28);
    doc.text(`Total Words: ${words.length}`, 140, 28);

    // 3. Table Structure
    const tableColumn = ["Check", "Words", "Meaning"];
    const tableRows: any[] = [];

    words.forEach(word => {
        const wordData = [
            "  ", // Checkbox placeholder
            word.word,
            word.meaning
        ];
        tableRows.push(wordData);
    });

    // 4. Generate Table
    autoTable(doc, {
        head: [tableColumn],
        body: tableRows,
        startY: 35,
        styles: {
            font: 'NotoSansKR',
            fontSize: 10,
            cellPadding: 3,
        },
        headStyles: {
            fillColor: [63, 81, 181], // Blue color
            textColor: 255,
            fontStyle: 'bold',
        },
        columnStyles: {
            0: { cellWidth: 15, halign: 'center' }, // Check
            1: { cellWidth: 60, fontStyle: 'bold' }, // Words
            2: { cellWidth: 'auto' }, // Meaning
        },
        // Alternate row colors
        theme: 'grid',
    });

    // 5. Test Sheet (Page 2) - Blank Meanings
    doc.addPage();
    doc.setFontSize(16);
    doc.text(`${title} - TEST (Meaning)`, 14, 20);

    const testRowsMeaning: any[] = [];
    words.forEach(word => {
        testRowsMeaning.push(["  ", word.word, " "]); // Meaning is blank
    });

    autoTable(doc, {
        head: [["Check", "Words", "Meaning (Write here)"]],
        body: testRowsMeaning,
        startY: 30,
        styles: { font: 'NotoSansKR', fontSize: 10, cellPadding: 3 },
        headStyles: { fillColor: [233, 30, 99], textColor: 255 }, // Pink
        columnStyles: {
            0: { cellWidth: 15, halign: 'center' },
            1: { cellWidth: 60, fontStyle: 'bold' },
            2: { cellWidth: 'auto' }
        },
        theme: 'grid',
    });

    // 6. Test Sheet (Page 3) - Blank Words
    doc.addPage();
    doc.setFontSize(16);
    doc.text(`${title} - TEST (Word)`, 14, 20);

    const testRowsWord: any[] = [];
    words.forEach(word => {
        testRowsWord.push(["  ", " ", word.meaning]); // Word is blank
    });

    autoTable(doc, {
        head: [["Check", "Words (Write here)", "Meaning"]],
        body: testRowsWord,
        startY: 30,
        styles: { font: 'NotoSansKR', fontSize: 10, cellPadding: 3 },
        headStyles: { fillColor: [0, 150, 136], textColor: 255 }, // Teal
        columnStyles: {
            0: { cellWidth: 15, halign: 'center' },
            1: { cellWidth: 60 },
            2: { cellWidth: 'auto' }
        },
        theme: 'grid',
    });

    // 7. Save
    doc.save(`VocaMaster_${title.replace(/\s+/g, '_')}.pdf`);
}
