// 중등 필수 단어 1000개 (8개 분야 × 125개)
// Format: "word|의미|/발음/|동의어1,동의어2|반의어1,반의어2"
module.exports = {
    society: [
        "community|공동체, 지역사회|/kəˈmjuːnəti/|society,group|individual",
        "citizen|시민|/ˈsɪtɪzn/|resident,inhabitant|foreigner",
        "government|정부|/ˈɡʌvərnmənt/|administration,authority|anarchy",
        "vote|투표하다|/voʊt/|elect,choose|abstain",
        "law|법, 법률|/lɔː/|rule,regulation|chaos",
        "right|권리|/raɪt/|privilege,entitlement|obligation",
        "duty|의무, 책임|/ˈdjuːti/|responsibility,obligation|privilege",
        "freedom|자유|/ˈfriːdəm/|liberty,independence|captivity",
        "peace|평화|/piːs/|harmony,calm|war,conflict",
        "justice|정의, 공정|/ˈdʒʌstɪs/|fairness,equity|injustice",
        "society|사회|/səˈsaɪəti/|community,civilization|isolation",
        "public|공공의, 대중|/ˈpʌblɪk/|common,general|private",
        "policy|정책|/ˈpɒləsi/|plan,strategy|",
        "population|인구|/ˌpɒpjuˈleɪʃn/|people,inhabitants|",
        "crime|범죄|/kraɪm/|offense,violation|virtue",
        "safety|안전|/ˈseɪfti/|security,protection|danger",
        "volunteer|자원봉사자|/ˌvɒlənˈtɪr/|helper,supporter|",
        "neighbor|이웃|/ˈneɪbər/|resident,fellow|stranger",
        "respect|존경, 존중|/rɪˈspekt/|admiration,esteem|disrespect",
        "equal|평등한, 동등한|/ˈiːkwəl/|even,identical|unequal",
        "protest|항의, 시위|/ˈproʊtest/|demonstration,objection|agreement",
        "welfare|복지|/ˈwelfer/|well-being,prosperity|hardship",
        "tradition|전통|/trəˈdɪʃn/|custom,heritage|innovation",
        "responsibility|책임|/rɪˌspɒnsəˈbɪləti/|duty,obligation|irresponsibility",
        "cooperation|협력|/koʊˌɒpəˈreɪʃn/|collaboration,teamwork|competition",
        "debate|토론, 논쟁|/dɪˈbeɪt/|discussion,argument|agreement",
        "opinion|의견|/əˈpɪnjən/|view,belief|fact",
        "conflict|갈등, 충돌|/ˈkɒnflɪkt/|dispute,clash|harmony",
        "charity|자선|/ˈtʃærəti/|donation,generosity|greed",
        "poverty|가난, 빈곤|/ˈpɒvərti/|hardship,need|wealth",
        "elderly|노인, 어르신|/ˈeldərli/|senior,aged|young",
        "immigrant|이민자|/ˈɪmɪɡrənt/|migrant,newcomer|native",
        "minority|소수, 소수집단|/maɪˈnɒrəti/|few,smaller group|majority",
        "culture|문화|/ˈkʌltʃər/|civilization,heritage|barbarism",
        "custom|관습, 풍습|/ˈkʌstəm/|practice,habit|novelty",
        "moral|도덕적인|/ˈmɒrəl/|ethical,righteous|immoral",
        "social|사회적인|/ˈsoʊʃl/|communal,public|individual",
        "diverse|다양한|/daɪˈvɜːrs/|varied,different|uniform",
        "discrimination|차별|/dɪˌskrɪmɪˈneɪʃn/|prejudice,bias|equality",
        "privilege|특권|/ˈprɪvəlɪdʒ/|advantage,benefit|disadvantage",
        "democracy|민주주의|/dɪˈmɒkrəsi/|self-government,republic|dictatorship",
        "election|선거|/ɪˈlekʃn/|poll,ballot|",
        "authority|당국, 권위|/ɔːˈθɒrəti/|power,control|weakness",
        "attitude|태도|/ˈætɪtjuːd/|manner,approach|",
        "ceremony|의식, 행사|/ˈserɪmoʊni/|ritual,celebration|",
        "convention|관례, 대회|/kənˈvenʃn/|custom,tradition|",
        "participation|참여|/pɑːrˌtɪsɪˈpeɪʃn/|involvement,engagement|exclusion",
        "agreement|합의, 동의|/əˈɡriːmənt/|deal,contract|disagreement",
        "regulation|규정, 규제|/ˌreɡjuˈleɪʃn/|rule,guideline|deregulation",
        "penalty|벌금, 처벌|/ˈpenəlti/|punishment,fine|reward",
        "permit|허가하다|/pərˈmɪt/|allow,authorize|prohibit",
        "complaint|불만, 불평|/kəmˈpleɪnt/|objection,grievance|compliment",
        "violence|폭력|/ˈvaɪələns/|aggression,brutality|peace",
        "reform|개혁|/rɪˈfɔːrm/|change,improvement|stagnation",
        "unity|단결, 통합|/ˈjuːnəti/|togetherness,solidarity|division",
        "campaign|캠페인, 운동|/kæmˈpeɪn/|movement,drive|",
        "civil|시민의|/ˈsɪvl/|civilian,public|military",
        "community service|지역 봉사|/kəˈmjuːnəti ˈsɜːvɪs/|volunteer work|",
        "heritage|유산|/ˈherɪtɪdʒ/|legacy,inheritance|",
        "identity|정체성|/aɪˈdentəti/|character,individuality|anonymity",
        "influence|영향, 영향력|/ˈɪnfluəns/|impact,effect|insignificance",
        "leadership|리더십, 지도력|/ˈliːdərʃɪp/|guidance,direction|",
        "organization|조직, 단체|/ˌɔːrɡənɪˈzeɪʃn/|group,institution|disorganization",
        "principle|원칙|/ˈprɪnsəpl/|belief,standard|",
        "relationship|관계|/rɪˈleɪʃnʃɪp/|connection,bond|isolation",
        "religion|종교|/rɪˈlɪdʒən/|faith,belief|atheism",
        "rural|시골의|/ˈrʊrəl/|countryside,pastoral|urban",
        "urban|도시의|/ˈɜːrbən/|metropolitan,city|rural",
        "welfare state|복지 국가|/ˈwelfer steɪt/|social state|",
        "youth|청소년, 젊은이|/juːθ/|teenager,adolescent|elder",
        "tolerance|관용, 인내|/ˈtɒlərəns/|acceptance,patience|intolerance",
        "independence|독립|/ˌɪndɪˈpendəns/|autonomy,freedom|dependence",
        "gender|성별|/ˈdʒendər/|sex|",
        "equality|평등|/ɪˈkwɒləti/|fairness,parity|inequality",
        "norm|규범, 기준|/nɔːrm/|standard,rule|exception",
        "community center|커뮤니티 센터|/kəˈmjuːnəti ˈsentər/|civic center|",
        "civil rights|시민권|/ˈsɪvl raɪts/|human rights|",
        "dignity|존엄, 품위|/ˈdɪɡnəti/|honor,self-respect|humiliation",
        "ethnic|민족의|/ˈeθnɪk/|racial,cultural|",
        "fair|공정한|/fer/|just,impartial|unfair",
        "harm|해, 손해|/hɑːrm/|damage,injury|benefit",
        "homeless|노숙자의|/ˈhoʊmləs/|displaced,unsheltered|housed",
        "ideal|이상적인|/aɪˈdiːəl/|perfect,model|imperfect",
        "immigrant|이주민|/ˈɪmɪɡrənt/|settler,newcomer|emigrant",
        "institution|기관, 제도|/ˌɪnstɪˈtjuːʃn/|organization,establishment|",
        "majority|다수, 대부분|/məˈdʒɒrəti/|most,bulk|minority",
        "movement|운동|/ˈmuːvmənt/|campaign,drive|stillness",
        "neighborhood|이웃, 동네|/ˈneɪbərhʊd/|area,community|",
        "obligation|의무|/ˌɒblɪˈɡeɪʃn/|duty,requirement|option",
        "poverty line|빈곤선|/ˈpɒvərti laɪn/|poverty level|",
        "prejudice|편견|/ˈpredʒudɪs/|bias,discrimination|fairness",
        "privacy|사생활, 프라이버시|/ˈpraɪvəsi/|secrecy,confidentiality|publicity",
        "public opinion|여론|/ˈpʌblɪk əˈpɪnjən/|popular view|",
        "racism|인종 차별주의|/ˈreɪsɪzm/|bigotry,discrimination|tolerance",
        "security|보안, 안전|/sɪˈkjʊrəti/|protection,safety|vulnerability",
        "shelter|보호소, 피난처|/ˈʃeltər/|refuge,haven|exposure",
        "symbol|상징|/ˈsɪmbl/|sign,emblem|",
        "unity|연대, 통합|/ˈjuːnɪti/|solidarity,union|division",
        "victim|피해자|/ˈvɪktɪm/|sufferer,casualty|perpetrator",
        "welfare program|복지 프로그램|/ˈwelfer ˈproʊɡræm/|social program|",
        "witness|목격자, 증인|/ˈwɪtnəs/|observer,spectator|",
        "debate team|토론팀|/dɪˈbeɪt tiːm/|discussion group|",
        "social media|소셜 미디어|/ˈsoʊʃl ˈmiːdiə/|online platform|",
        "bully|괴롭히다, 왕따|/ˈbʊli/|harass,intimidate|defend",
        "compromise|타협, 양보|/ˈkɒmprəmaɪz/|settlement,agreement|stalemate",
        "council|의회, 위원회|/ˈkaʊnsl/|committee,board|",
        "demonstrate|시위하다, 보여주다|/ˈdemənstreɪt/|show,protest|conceal",
        "disaster|재난|/dɪˈzæstər/|catastrophe,calamity|blessing",
        "donate|기부하다|/doʊˈneɪt/|give,contribute|take",
        "empathy|공감|/ˈempəθi/|sympathy,compassion|apathy",
        "fund|기금, 자금|/fʌnd/|money,capital|debt",
        "generous|관대한|/ˈdʒenərəs/|giving,charitable|selfish",
        "guilty|유죄인, 죄책감|/ˈɡɪlti/|culpable,responsible|innocent",
        "honor|명예, 존경|/ˈɒnər/|glory,respect|dishonor",
        "illegal|불법의|/ɪˈliːɡl/|unlawful,criminal|legal",
        "innocent|무죄의, 순진한|/ˈɪnəsnt/|guiltless,pure|guilty",
        "judge|판사, 판단하다|/dʒʌdʒ/|referee,evaluate|",
        "loyal|충성스러운|/ˈlɔɪəl/|faithful,devoted|disloyal",
        "mercy|자비, 관용|/ˈmɜːrsi/|compassion,forgiveness|cruelty",
        "obey|복종하다|/oʊˈbeɪ/|follow,comply|disobey",
        "patriot|애국자|/ˈpeɪtriət/|nationalist,loyalist|traitor",
        "refugee|난민|/ˌrefjuˈdʒiː/|exile,displaced person|citizen",
        "sacrifice|희생|/ˈsækrɪfaɪs/|offering,surrender|gain",
        "slavery|노예 제도|/ˈsleɪvəri/|bondage,servitude|freedom",
        "speech|연설|/spiːtʃ/|address,talk|silence",
        "struggle|투쟁, 노력|/ˈstrʌɡl/|fight,effort|ease",
    ],
    economy: [
        "money|돈|/ˈmʌni/|cash,currency|debt",
        "price|가격|/praɪs/|cost,value|",
        "trade|무역, 거래|/treɪd/|commerce,exchange|",
        "sell|팔다|/sel/|market,vend|buy",
        "buy|사다|/baɪ/|purchase,acquire|sell",
        "pay|지불하다|/peɪ/|compensate,settle|owe",
        "save|저축하다|/seɪv/|store,preserve|spend",
        "earn|벌다|/ɜːrn/|gain,make|lose",
        "spend|쓰다, 소비하다|/spend/|use,consume|save",
        "profit|이익, 수익|/ˈprɒfɪt/|gain,earnings|loss",
        "market|시장|/ˈmɑːrkɪt/|marketplace,bazaar|",
        "business|사업, 기업|/ˈbɪznəs/|company,firm|",
        "customer|고객|/ˈkʌstəmər/|client,buyer|seller",
        "product|제품, 상품|/ˈprɒdʌkt/|goods,item|",
        "service|서비스|/ˈsɜːrvɪs/|assistance,help|",
        "salary|급여, 월급|/ˈsæləri/|wage,pay|",
        "income|수입, 소득|/ˈɪnkʌm/|revenue,earnings|expense",
        "expense|비용, 경비|/ɪkˈspens/|cost,charge|income",
        "tax|세금|/tæks/|levy,duty|",
        "bank|은행|/bæŋk/|financial institution|",
        "invest|투자하다|/ɪnˈvest/|fund,finance|withdraw",
        "budget|예산|/ˈbʌdʒɪt/|plan,allowance|",
        "debt|빚, 부채|/det/|loan,liability|credit",
        "loan|대출|/loʊn/|lending,advance|repayment",
        "interest|이자, 관심|/ˈɪntrəst/|attention,concern|indifference",
        "economy|경제|/ɪˈkɒnəmi/|finance,commerce|",
        "industry|산업|/ˈɪndəstri/|business,manufacturing|",
        "factory|공장|/ˈfæktəri/|plant,workshop|",
        "employment|고용|/ɪmˈplɔɪmənt/|work,job|unemployment",
        "unemployment|실업|/ˌʌnɪmˈplɔɪmənt/|joblessness|employment",
        "wage|임금|/weɪdʒ/|pay,salary|",
        "advertisement|광고|/ˌædvərˈtaɪzmənt/|promotion,commercial|",
        "brand|브랜드, 상표|/brænd/|label,trademark|",
        "discount|할인|/ˈdɪskaʊnt/|reduction,sale|surcharge",
        "export|수출|/ˈekspɔːrt/|ship,sell abroad|import",
        "import|수입|/ˈɪmpɔːrt/|bring in,purchase|export",
        "exchange|교환, 환전|/ɪksˈtʃeɪndʒ/|swap,trade|keep",
        "demand|수요|/dɪˈmænd/|need,request|supply",
        "supply|공급|/səˈplaɪ/|provide,furnish|demand",
        "goods|상품, 물품|/ɡʊdz/|merchandise,products|",
        "benefit|이익, 혜택|/ˈbenɪfɪt/|advantage,gain|disadvantage",
        "contract|계약|/ˈkɒntrækt/|agreement,deal|",
        "consumer|소비자|/kənˈsjuːmər/|buyer,shopper|producer",
        "producer|생산자|/prəˈdjuːsər/|manufacturer,maker|consumer",
        "compete|경쟁하다|/kəmˈpiːt/|rival,contest|cooperate",
        "competition|경쟁|/ˌkɒmpəˈtɪʃn/|contest,rivalry|cooperation",
        "afford|여유가 되다|/əˈfɔːrd/|manage,spare|",
        "bargain|흥정, 싸게 사다|/ˈbɑːrɡɪn/|deal,negotiate|",
        "charge|청구하다, 요금|/tʃɑːrdʒ/|fee,cost|",
        "commerce|상업|/ˈkɒmɜːrs/|trade,business|",
        "corporation|기업, 법인|/ˌkɔːrpəˈreɪʃn/|company,firm|",
        "currency|통화, 화폐|/ˈkɜːrənsi/|money,cash|",
        "deposit|예금, 보증금|/dɪˈpɒzɪt/|savings,payment|withdrawal",
        "economic|경제적인|/ˌiːkəˈnɒmɪk/|financial,monetary|",
        "fortune|재산, 행운|/ˈfɔːrtʃən/|wealth,riches|poverty",
        "insurance|보험|/ɪnˈʃʊrəns/|coverage,protection|",
        "manufacture|제조하다|/ˌmænjuˈfæktʃər/|produce,make|",
        "merchant|상인|/ˈmɜːrtʃənt/|trader,dealer|buyer",
        "opportunity|기회|/ˌɒpərˈtjuːnəti/|chance,opening|obstacle",
        "payment|지불, 납부|/ˈpeɪmənt/|settlement,remittance|",
        "profit margin|이윤|/ˈprɒfɪt ˈmɑːrdʒɪn/|markup,gain|",
        "purchase|구매하다|/ˈpɜːrtʃəs/|buy,acquire|sell",
        "receipt|영수증|/rɪˈsiːt/|bill,ticket|",
        "resource|자원|/rɪˈsɔːrs/|supply,asset|",
        "retail|소매|/ˈriːteɪl/|selling,merchandising|wholesale",
        "revenue|수입, 세입|/ˈrevənjuː/|income,earnings|expense",
        "stock|주식, 재고|/stɒk/|share,supply|",
        "value|가치|/ˈvæljuː/|worth,merit|worthlessness",
        "wealth|부, 재산|/welθ/|riches,fortune|poverty",
        "wholesale|도매|/ˈhoʊlseɪl/|bulk selling|retail",
        "account|계좌, 계정|/əˈkaʊnt/|record,register|",
        "asset|자산|/ˈæset/|property,resource|liability",
        "auction|경매|/ˈɔːkʃn/|bidding,sale|",
        "bankrupt|파산한|/ˈbæŋkrʌpt/|insolvent,broke|wealthy",
        "capital|자본, 수도|/ˈkæpɪtl/|funds,wealth|",
        "cashier|계산원|/kæˈʃɪr/|clerk,teller|",
        "cost|비용|/kɒst/|price,expense|",
        "credit|신용, 학점|/ˈkredɪt/|trust,loan|debit",
        "deal|거래|/diːl/|agreement,transaction|",
        "donate|기부하다|/doʊˈneɪt/|give,contribute|receive",
        "entrepreneur|기업가|/ˌɒntrəprəˈnɜːr/|businessman,founder|employee",
        "fee|수수료, 요금|/fiː/|charge,cost|",
        "financial|재정적인|/faɪˈnænʃl/|monetary,fiscal|",
        "guarantee|보증|/ˌɡærənˈtiː/|warranty,assurance|",
        "hire|고용하다|/haɪər/|employ,recruit|fire",
        "labor|노동|/ˈleɪbər/|work,toil|rest",
        "luxury|사치, 호화|/ˈlʌkʃəri/|extravagance,opulence|necessity",
        "offer|제안하다|/ˈɒfər/|propose,suggest|refuse",
        "owe|빚지다|/oʊ/|be indebted|repay",
        "partner|파트너, 동반자|/ˈpɑːrtnər/|associate,colleague|rival",
        "poverty|극빈|/ˈpɒvərti/|destitution,need|affluence",
        "profession|직업|/prəˈfeʃn/|career,occupation|",
        "property|재산, 부동산|/ˈprɒpərti/|estate,possession|",
        "qualification|자격|/ˌkwɒlɪfɪˈkeɪʃn/|credential,skill|",
        "refund|환불|/ˈriːfʌnd/|reimbursement,return|",
        "rent|임대료, 빌리다|/rent/|lease,hire|own",
        "shortage|부족|/ˈʃɔːrtɪdʒ/|deficit,scarcity|surplus",
        "thrift|절약|/θrɪft/|frugality,economy|waste",
        "transaction|거래|/trænˈzækʃn/|deal,exchange|",
        "warehouse|창고|/ˈwerhaʊs/|storehouse,depot|",
        "yield|산출하다, 수확|/jiːld/|produce,generate|consume",
        "allowance|용돈, 수당|/əˈlaʊəns/|stipend,pocket money|",
        "balance|잔액, 균형|/ˈbæləns/|remainder,equilibrium|imbalance",
        "bid|입찰하다|/bɪd/|offer,tender|",
        "bill|청구서, 지폐|/bɪl/|invoice,check|",
        "bonus|보너스, 상여금|/ˈboʊnəs/|extra,reward|penalty",
        "borrow|빌리다|/ˈbɒroʊ/|loan,lend|return",
        "brand name|브랜드명|/brænd neɪm/|trademark,label|",
        "career|직업, 경력|/kəˈrɪr/|profession,vocation|",
        "chain store|체인점|/tʃeɪn stɔːr/|franchise|",
        "clerk|사무원, 점원|/klɜːrk/|assistant,employee|",
        "coin|동전|/kɔɪn/|change,piece|",
        "commodity|상품, 물자|/kəˈmɒdəti/|goods,product|",
        "coupon|쿠폰|/ˈkuːpɒn/|voucher,ticket|",
        "efficiency|효율|/ɪˈfɪʃnsi/|productivity,effectiveness|inefficiency",
        "fund|기금|/fʌnd/|capital,money|",
        "groceries|식료품|/ˈɡroʊsəriz/|provisions,food|",
        "headquarters|본사|/ˈhedkwɔːrtərz/|main office,base|branch",
        "inflation|인플레이션|/ɪnˈfleɪʃn/|price rise|deflation",
        "inventory|재고, 목록|/ˈɪnvəntɔːri/|stock,supply|",
        "invest|투자하다|/ɪnˈvest/|put money in|divest",
        "management|관리, 경영|/ˈmænɪdʒmənt/|administration,control|",
        "marketing|마케팅|/ˈmɑːrkɪtɪŋ/|advertising,promotion|",
        "negotiate|협상하다|/nɪˈɡoʊʃieɪt/|bargain,discuss|",
        "profit|이윤|/ˈprɒfɪt/|earnings,gain|loss",
        "promote|홍보하다, 승진시키다|/prəˈmoʊt/|advertise,advance|demote",
    ],
    nature: [
        "weather|날씨|/ˈweðər/|climate,conditions|",
        "climate|기후|/ˈklaɪmət/|weather pattern|",
        "forest|숲|/ˈfɒrɪst/|woods,woodland|desert",
        "river|강|/ˈrɪvər/|stream,waterway|",
        "ocean|바다, 대양|/ˈoʊʃn/|sea,marine|land",
        "mountain|산|/ˈmaʊntən/|peak,summit|valley",
        "earth|지구, 흙|/ɜːrθ/|planet,soil|sky",
        "plant|식물|/plænt/|vegetation,flora|animal",
        "animal|동물|/ˈænɪml/|creature,beast|plant",
        "flower|꽃|/ˈflaʊər/|blossom,bloom|",
        "tree|나무|/triː/|timber,wood|",
        "rain|비|/reɪn/|rainfall,shower|drought",
        "snow|눈|/snoʊ/|snowfall,frost|",
        "wind|바람|/wɪnd/|breeze,gust|calm",
        "sun|태양|/sʌn/|sunlight,star|moon",
        "moon|달|/muːn/|satellite,lunar|sun",
        "star|별|/stɑːr/|celestial body|",
        "sky|하늘|/skaɪ/|atmosphere,heavens|ground",
        "soil|토양,흙|/sɔɪl/|earth,ground|",
        "seed|씨앗|/siːd/|grain,kernel|",
        "root|뿌리|/ruːt/|base,foundation|branch",
        "leaf|잎|/liːf/|foliage,blade|",
        "branch|가지|/bræntʃ/|limb,bough|root",
        "wave|파도|/weɪv/|surge,swell|calm",
        "island|섬|/ˈaɪlənd/|isle,atoll|mainland",
        "lake|호수|/leɪk/|pond,reservoir|",
        "desert|사막|/ˈdezərt/|wasteland,barren|oasis",
        "volcano|화산|/vɒlˈkeɪnoʊ/|mountain,crater|",
        "earthquake|지진|/ˈɜːrθkweɪk/|tremor,quake|",
        "flood|홍수|/flʌd/|overflow,deluge|drought",
        "drought|가뭄|/draʊt/|dry spell,aridity|flood",
        "pollution|오염|/pəˈluːʃn/|contamination,smog|purity",
        "environment|환경|/ɪnˈvaɪrənmənt/|surroundings,habitat|",
        "recycle|재활용하다|/ˌriːˈsaɪkl/|reuse,repurpose|waste",
        "protect|보호하다|/prəˈtekt/|guard,defend|harm",
        "endangered|멸종 위기의|/ɪnˈdeɪndʒərd/|threatened,at risk|safe",
        "species|종, 생물 종|/ˈspiːʃiːz/|type,kind|",
        "ecosystem|생태계|/ˈiːkoʊsɪstəm/|habitat,biome|",
        "habitat|서식지|/ˈhæbɪtæt/|home,environment|",
        "wildlife|야생 동물|/ˈwaɪldlaɪf/|fauna,animals|",
        "conservation|보존|/ˌkɒnsərˈveɪʃn/|preservation,protection|destruction",
        "renewable|재생 가능한|/rɪˈnjuːəbl/|sustainable|nonrenewable",
        "solar|태양의|/ˈsoʊlər/|sun-powered|",
        "temperature|온도, 기온|/ˈtemprətʃər/|heat,warmth|",
        "atmosphere|대기|/ˈætməsfɪr/|air,sky|",
        "oxygen|산소|/ˈɒksɪdʒən/|O2,air|",
        "carbon|탄소|/ˈkɑːrbən/|element|",
        "greenhouse|온실|/ˈɡriːnhaʊs/|hothouse|",
        "global warming|지구 온난화|/ˈɡloʊbl ˈwɔːrmɪŋ/|climate change|",
        "waste|쓰레기, 낭비|/weɪst/|garbage,trash|conservation",
        "natural|자연의|/ˈnætʃərəl/|organic,native|artificial",
        "organic|유기적인|/ɔːrˈɡænɪk/|natural,bio|synthetic",
        "resource|자원|/rɪˈsɔːrs/|supply,material|",
        "disaster|재해|/dɪˈzæstər/|catastrophe,calamity|fortune",
        "coast|해안|/koʊst/|shore,seaside|inland",
        "cliff|절벽|/klɪf/|bluff,precipice|valley",
        "jungle|정글|/ˈdʒʌŋɡl/|rainforest,bush|",
        "meadow|초원, 목초지|/ˈmedoʊ/|field,pasture|",
        "stream|시냇물|/striːm/|creek,brook|",
        "waterfall|폭포|/ˈwɔːtərfɔːl/|cascade,falls|",
        "coral|산호|/ˈkɒrəl/|reef|",
        "fossil|화석|/ˈfɒsl/|remains,relic|",
        "mineral|광물|/ˈmɪnərəl/|ore,crystal|",
        "landscape|풍경, 경관|/ˈlændskeɪp/|scenery,view|",
        "wildlife reserve|야생 보호구역|/ˈwaɪldlaɪf rɪˈzɜːrv/|nature park|",
        "hurricane|허리케인|/ˈhɜːrɪkeɪn/|typhoon,cyclone|calm",
        "tornado|토네이도|/tɔːrˈneɪdoʊ/|twister,cyclone|",
        "tsunami|쓰나미|/tsuːˈnɑːmi/|tidal wave|",
        "glacier|빙하|/ˈɡleɪʃər/|ice sheet,iceberg|",
        "wetland|습지|/ˈwetlænd/|marsh,swamp|dryland",
        "erosion|침식|/ɪˈroʊʒn/|wearing away|buildup",
        "harvest|수확|/ˈhɑːrvɪst/|crop,yield|sow",
        "bloom|꽃이 피다|/bluːm/|blossom,flower|wilt",
        "fertile|비옥한|/ˈfɜːrtaɪl/|productive,rich|barren",
        "migrate|이동하다|/ˈmaɪɡreɪt/|travel,move|stay",
        "prey|먹이|/preɪ/|target,quarry|predator",
        "predator|포식자|/ˈpredətər/|hunter|prey",
        "nest|둥지|/nest/|den,home|",
        "hibernate|동면하다|/ˈhaɪbərneɪt/|sleep,rest|awaken",
        "tropical|열대의|/ˈtrɒpɪkl/|warm,equatorial|arctic",
        "arctic|북극의|/ˈɑːrktɪk/|polar,frozen|tropical",
        "creature|생물|/ˈkriːtʃər/|being,organism|",
        "insect|곤충|/ˈɪnsekt/|bug,pest|",
        "mammal|포유류|/ˈmæml/|warm-blooded animal|",
        "reptile|파충류|/ˈreptaɪl/|lizard,snake|",
        "amphibian|양서류|/æmˈfɪbiən/|frog,salamander|",
        "marine|해양의|/məˈriːn/|oceanic,sea|terrestrial",
        "vegetation|초목, 식물|/ˌvedʒəˈteɪʃn/|greenery,plants|",
        "ecology|생태학|/ɪˈkɒlədʒi/|environmental science|",
        "deforestation|삼림 벌채|/diːˌfɒrɪˈsteɪʃn/|logging,clearing|reforestation",
        "reforestation|재조림|/ˌriːˌfɒrɪˈsteɪʃn/|replanting|deforestation",
        "sustainable|지속 가능한|/səˈsteɪnəbl/|eco-friendly|unsustainable",
        "emission|배출|/ɪˈmɪʃn/|discharge,output|absorption",
        "biodiversity|생물 다양성|/ˌbaɪoʊdaɪˈvɜːrsəti/|variety of life|",
        "preserve|보존하다|/prɪˈzɜːrv/|maintain,protect|destroy",
        "dam|댐|/dæm/|barrier,reservoir|",
        "pond|연못|/pɒnd/|pool,lagoon|",
        "canyon|협곡|/ˈkænjən/|gorge,ravine|",
        "reef|산호초|/riːf/|coral formation|",
        "prairie|대초원|/ˈpreri/|grassland,plain|",
        "swamp|늪지|/swɒmp/|marsh,bog|dryland",
        "valley|계곡|/ˈvæli/|dale,glen|mountain",
        "peak|봉우리, 정상|/piːk/|summit,top|base",
        "tide|조수, 조류|/taɪd/|current,flow|",
        "shore|해변, 기슭|/ʃɔːr/|coast,beach|inland",
        "oasis|오아시스|/oʊˈeɪsɪs/|spring,refuge|desert",
        "peninsula|반도|/pəˈnɪnsələ/|cape,headland|island",
        "altitude|고도|/ˈæltɪtjuːd/|height,elevation|depth",
        "continent|대륙|/ˈkɒntɪnənt/|landmass|ocean",
        "orbit|궤도|/ˈɔːrbɪt/|path,revolution|",
        "gravity|중력|/ˈɡrævəti/|pull,attraction|weightlessness",
        "crystal|수정, 결정|/ˈkrɪstl/|gem,mineral|",
        "dew|이슬|/djuː/|moisture,condensation|",
        "frost|서리|/frɒst/|ice,freeze|thaw",
        "hail|우박|/heɪl/|ice pellets|",
        "fog|안개|/fɒɡ/|mist,haze|clarity",
        "thunder|천둥|/ˈθʌndər/|rumble,boom|silence",
        "lightning|번개|/ˈlaɪtnɪŋ/|bolt,flash|",
        "rainbow|무지개|/ˈreɪnboʊ/|spectrum,arc|",
        "breeze|미풍, 산들바람|/briːz/|gentle wind|storm",
        "current|해류, 조류|/ˈkʌrənt/|flow,stream|",
        "pollen|꽃가루|/ˈpɒlən/|spore,grain|",
        "trunk|나무 줄기|/trʌŋk/|stem,bole|",
    ],
    science: [
        "experiment|실험|/ɪkˈsperɪmənt/|test,trial|theory",
        "discover|발견하다|/dɪˈskʌvər/|find,uncover|conceal",
        "invent|발명하다|/ɪnˈvent/|create,devise|copy",
        "machine|기계|/məˈʃiːn/|device,apparatus|",
        "energy|에너지|/ˈenərdʒi/|power,force|exhaustion",
        "technology|기술|/tekˈnɒlədʒi/|innovation,technique|",
        "computer|컴퓨터|/kəmˈpjuːtər/|PC,laptop|",
        "device|장치, 기기|/dɪˈvaɪs/|gadget,tool|",
        "electric|전기의|/ɪˈlektrɪk/|powered,electronic|manual",
        "robot|로봇|/ˈroʊbɒt/|automaton,machine|human",
        "microscope|현미경|/ˈmaɪkrəskoʊp/|magnifier|telescope",
        "telescope|망원경|/ˈtelɪskoʊp/|viewer|microscope",
        "laboratory|실험실|/ˈlæbrətɔːri/|lab,workshop|",
        "data|데이터, 자료|/ˈdeɪtə/|information,facts|",
        "research|연구|/rɪˈsɜːrtʃ/|study,investigation|",
        "scientist|과학자|/ˈsaɪəntɪst/|researcher,scholar|",
        "theory|이론|/ˈθɪəri/|hypothesis,concept|practice",
        "formula|공식|/ˈfɔːrmjulə/|equation,recipe|",
        "chemical|화학적인, 화학물질|/ˈkemɪkl/|substance,compound|natural",
        "biology|생물학|/baɪˈɒlədʒi/|life science|",
        "physics|물리학|/ˈfɪzɪks/|science of matter|",
        "chemistry|화학|/ˈkemɪstri/|chemical science|",
        "digital|디지털의|/ˈdɪdʒɪtl/|electronic,virtual|analog",
        "internet|인터넷|/ˈɪntərnet/|web,online|offline",
        "software|소프트웨어|/ˈsɒftwer/|program,application|hardware",
        "hardware|하드웨어|/ˈhɑːrdwer/|equipment,machinery|software",
        "satellite|위성|/ˈsætəlaɪt/|orbiter,probe|",
        "artificial|인공적인|/ˌɑːrtɪˈfɪʃl/|synthetic,man-made|natural",
        "automatic|자동의|/ˌɔːtəˈmætɪk/|self-operating|manual",
        "battery|배터리, 전지|/ˈbætəri/|cell,power source|",
        "calculate|계산하다|/ˈkælkjuleɪt/|compute,figure|estimate",
        "circuit|회로|/ˈsɜːrkɪt/|loop,network|",
        "code|코드, 암호|/koʊd/|cipher,program|",
        "database|데이터베이스|/ˈdeɪtəbeɪs/|records,files|",
        "element|원소, 요소|/ˈelɪmənt/|component,part|whole",
        "engineer|공학자, 기술자|/ˌendʒɪˈnɪr/|technician,designer|",
        "evolution|진화|/ˌiːvəˈluːʃn/|development,progress|regression",
        "fiber|섬유|/ˈfaɪbər/|thread,strand|",
        "frequency|주파수, 빈도|/ˈfriːkwənsi/|rate,regularity|rarity",
        "fuel|연료|/fjuːəl/|gas,petroleum|",
        "galaxy|은하|/ˈɡæləksi/|star system,cosmos|",
        "gene|유전자|/dʒiːn/|DNA,heredity unit|",
        "gravity|중력|/ˈɡrævəti/|pull,force|weightlessness",
        "hydrogen|수소|/ˈhaɪdrədʒən/|H2,element|",
        "innovation|혁신|/ˌɪnəˈveɪʃn/|invention,breakthrough|tradition",
        "laser|레이저|/ˈleɪzər/|beam,light|",
        "lens|렌즈|/lenz/|glass,optic|",
        "magnet|자석|/ˈmæɡnət/|attractor|",
        "molecule|분자|/ˈmɒlɪkjuːl/|particle,unit|",
        "network|네트워크|/ˈnetwɜːrk/|system,web|",
        "nuclear|핵의|/ˈnjuːkliər/|atomic|",
        "organism|유기체, 생물|/ˈɔːrɡənɪzm/|living thing,creature|",
        "oxygen|산소|/ˈɒksɪdʒən/|O2|",
        "particle|입자|/ˈpɑːrtɪkl/|atom,speck|whole",
        "planet|행성|/ˈplænɪt/|world,sphere|star",
        "program|프로그램|/ˈproʊɡræm/|software,application|",
        "radiation|방사선|/ˌreɪdiˈeɪʃn/|emission,rays|",
        "reaction|반응|/riˈækʃn/|response,reply|action",
        "signal|신호|/ˈsɪɡnəl/|sign,indicator|",
        "solar system|태양계|/ˈsoʊlər ˈsɪstəm/|planetary system|",
        "specimen|표본|/ˈspesɪmən/|sample,example|",
        "spectrum|스펙트럼|/ˈspektrəm/|range,band|",
        "substance|물질|/ˈsʌbstəns/|material,matter|",
        "surgery|수술|/ˈsɜːrdʒəri/|operation,procedure|",
        "vaccine|백신|/vækˈsiːn/|immunization,shot|",
        "virus|바이러스|/ˈvaɪrəs/|germ,pathogen|",
        "virtual|가상의|/ˈvɜːrtʃuəl/|simulated,digital|real",
        "wireless|무선의|/ˈwaɪərləs/|cordless,radio|wired",
        "algorithm|알고리즘|/ˈælɡərɪðəm/|procedure,method|",
        "atom|원자|/ˈætəm/|particle,unit|",
        "bacteria|박테리아|/bækˈtɪriə/|germs,microbes|",
        "cell|세포|/sel/|unit,organism|",
        "chromosome|염색체|/ˈkroʊməsoʊm/|DNA structure|",
        "clone|복제|/kloʊn/|copy,duplicate|original",
        "conductor|도체, 전도체|/kənˈdʌktər/|transmitter|insulator",
        "density|밀도|/ˈdensəti/|thickness,concentration|thinness",
        "diameter|지름|/daɪˈæmɪtər/|width,breadth|radius",
        "dimension|차원, 크기|/daɪˈmenʃn/|size,extent|",
        "electricity|전기|/ɪˌlekˈtrɪsəti/|power,current|",
        "electron|전자|/ɪˈlektrɒn/|particle|proton",
        "force|힘|/fɔːrs/|power,strength|weakness",
        "friction|마찰|/ˈfrɪkʃn/|resistance,rubbing|smoothness",
        "function|기능|/ˈfʌŋkʃn/|role,purpose|malfunction",
        "gear|기어, 장비|/ɡɪr/|mechanism,equipment|",
        "genetic|유전적인|/dʒəˈnetɪk/|hereditary,inherited|acquired",
        "hypothesis|가설|/haɪˈpɒθəsɪs/|theory,assumption|fact",
        "infrared|적외선|/ˌɪnfrəˈred/|heat radiation|ultraviolet",
        "liquid|액체|/ˈlɪkwɪd/|fluid,solution|solid",
        "mass|질량|/mæs/|weight,bulk|",
        "matter|물질|/ˈmætər/|substance,material|",
        "mechanism|메커니즘|/ˈmekənɪzm/|system,process|",
        "method|방법|/ˈmeθəd/|technique,approach|",
        "microscopic|미세한|/ˌmaɪkrəˈskɒpɪk/|tiny,minute|macroscopic",
        "navigate|항해하다|/ˈnævɪɡeɪt/|steer,guide|",
        "neutron|중성자|/ˈnjuːtrɒn/|particle|",
        "observe|관찰하다|/əbˈzɜːrv/|watch,examine|ignore",
        "operate|작동하다|/ˈɒpəreɪt/|run,function|malfunction",
        "orbit|궤도|/ˈɔːrbɪt/|path,revolution|",
        "patent|특허|/ˈpætnt/|license,copyright|",
        "phenomenon|현상|/fɪˈnɒmɪnən/|event,occurrence|",
        "photon|광자|/ˈfoʊtɒn/|light particle|",
        "process|과정|/ˈprɒses/|procedure,method|",
        "prototype|원형, 시제품|/ˈproʊtətaɪp/|model,sample|final product",
        "quantum|양자|/ˈkwɒntəm/|unit,amount|",
        "radar|레이더|/ˈreɪdɑːr/|detection system|",
        "ratio|비율|/ˈreɪʃioʊ/|proportion,rate|",
        "semiconductor|반도체|/ˌsemiːkənˈdʌktər/|chip,silicon|",
        "sensor|센서|/ˈsensər/|detector,monitor|",
        "simulate|모의실험하다|/ˈsɪmjuleɪt/|imitate,model|",
        "static|정적인|/ˈstætɪk/|stationary,fixed|dynamic",
        "stem cell|줄기세포|/stem sel/|progenitor cell|",
        "synthetic|합성의|/sɪnˈθetɪk/|artificial,man-made|natural",
        "thermometer|온도계|/θərˈmɒmɪtər/|temperature gauge|",
        "transmit|전송하다|/trænzˈmɪt/|send,broadcast|receive",
        "ultraviolet|자외선|/ˌʌltrəˈvaɪələt/|UV radiation|infrared",
        "upgrade|업그레이드|/ˈʌpɡreɪd/|improve,enhance|downgrade",
        "velocity|속도|/vəˈlɒsəti/|speed,pace|stillness",
        "voltage|전압|/ˈvoʊltɪdʒ/|electric potential|",
        "volume|부피, 양|/ˈvɒljuːm/|capacity,amount|",
        "wavelength|파장|/ˈweɪvleŋθ/|frequency|",
        "x-ray|엑스레이|/ˈeks reɪ/|radiation scan|",
        "zoom|확대하다|/zuːm/|magnify,enlarge|minimize",
    ],
    // Part 2 will be appended via require
    ...require('./words-middle-p2.cjs'),
};
