// 고등 기초 후반부: science, culture, education, health, global
module.exports = {
    science: [
        "algorithm|알고리즘, 연산 절차", "apparatus|장치, 기구", "biodegradable|생분해성의",
        "biotechnology|생명공학", "calibrate|보정하다, 교정하다", "centrifuge|원심분리기",
        "cipher|암호", "combustion|연소", "compile|편집하다, 컴파일하다",
        "compute|계산하다", "cyber|사이버의", "decode|해독하다",
        "diffusion|확산", "diode|다이오드", "disperse|분산시키다",
        "ecosystem model|생태계 모델", "electromagnetic|전자기의", "emission spectrum|방출 스펙트럼",
        "encode|암호화하다", "entropy|엔트로피", "enzyme|효소",
        "equilibrium|평형, 균형", "erosion|침식", "evaporation|증발",
        "firmware|펌웨어", "fission|핵분열", "fluorescent|형광의",
        "fusion|핵융합", "genome|유전체", "geophysics|지구물리학",
        "gravitational|중력의", "incubate|배양하다", "inductance|인덕턴스",
        "integrate|통합하다", "isotope|동위원소", "kinetic|운동의",
        "lithium|리튬", "logarithm|로그, 대수", "malware|악성 소프트웨어",
        "membrane|막, 멤브레인", "metabolism|신진대사", "microchip|마이크로칩",
        "mitosis|유사분열", "modem|모뎀", "mutation|돌연변이",
        "nanotechnology|나노기술", "neural|신경의", "nucleus|핵",
        "nutrient|영양소", "optics|광학", "oscillate|진동하다",
        "oxidize|산화하다", "pathogen|병원체", "petroleum|석유",
        "pixel|픽셀", "plasma|플라즈마", "polymer|고분자",
        "propulsion|추진", "proton|양성자", "pulsar|펄서",
        "radioactive|방사성의", "reagent|시약", "refract|굴절시키다",
        "relativity|상대성", "resin|수지, 레진", "resonance|공명",
        "robotics|로봇공학", "seismic|지진의", "silicon|실리콘",
        "solubility|용해도", "sonar|소나", "spectroscopy|분광학",
        "strata|지층", "superconduct|초전도하다", "symbiotic|공생의",
        "terabyte|테라바이트", "thermal energy|열에너지", "thermostat|온도조절장치",
        "topology|위상수학", "transistor|트랜지스터", "turbine|터빈",
        "ultrasonic|초음파의", "variable|변수", "vector|벡터",
        "velocity|속력", "ventilate|환기하다", "viscosity|점성",
        "watt|와트", "xerography|전자사진술", "alloy|합금",
        "amplify|증폭하다", "analog|아날로그의", "anomaly|이상, 변칙",
        "asteroid|소행성", "atomic|원자의", "bandwidth|대역폭",
        "biometric|생체인식의", "boolean|불리언의", "celsius|섭씨",
        "centimeter|센티미터", "compatible|호환 가능한", "compress|압축하다",
        "constellation|별자리", "corrosion|부식", "cryogenic|극저온의",
        "decrypt|복호화하다", "diagnostic|진단의", "dissolve|용해하다",
        "drone|드론", "dynamo|발전기", "electrode|전극",
        "emit|방출하다", "encrypt|암호화하다", "exoplanet|외계 행성",
        "extract|추출하다", "filament|필라멘트", "geiger counter|가이거 계수기",
        "halogen|할로겐", "helium|헬리움", "hologram|홀로그램",
        "implant|이식하다", "incandescent|백열의", "interface|인터페이스",
        "ion|이온", "kinetics|동역학", "lithosphere|암석권",
        "magnitude|크기, 규모", "meteorite|운석", "milli|밀리",
        "nebula|성운", "neon|네온", "neutrino|중성미자",
        "oscilloscope|오실로스코프", "ozone layer|오존층", "paradox|역설",
        "pendulum|진자", "periodic table|주기율표", "permeable|투과성의",
        "piezoelectric|압전의", "polarity|극성", "precipitate|침전시키다",
        "prism|프리즘", "probe|탐사선", "quartz|석영",
        "receptor|수용체", "recombinant|재조합의", "semiconductor|반도체",
        "solvent|용매", "stratify|층화하다", "subatomic|원자 이하의",
        "supernova|초신성", "synapse|시냅스", "theorem|정리, 이론",
    ],
    culture: [
        "allegory|우화, 비유", "anthology|선집, 문집", "archetype|원형, 전형",
        "artifact|유물", "avant-garde|전위적인", "ballad|발라드, 민요",
        "baroque|바로크의", "batik|바틱", "calligrapher|서예가",
        "caricature|풍자화", "choreography|안무", "chronicle|연대기",
        "collage|콜라주", "curator|큐레이터", "decor|장식",
        "dystopia|디스토피아", "eclecticism|절충주의", "elegy|비가",
        "embroidery|자수", "ensemble|앙상블", "epic|서사시",
        "etching|에칭, 판화", "ethnography|민족지학", "expressionism|표현주의",
        "fable|우화", "facsimile|모사, 복사", "figurative|비유적인",
        "fresco|프레스코", "fugue|푸가", "gazette|관보",
        "graffiti|그래피티", "haiku|하이쿠", "harpsichord|하프시코드",
        "iconography|도상학", "idiom|관용어", "impersonation|흉내, 성대모사",
        "impressionism|인상주의", "impromptu|즉흥의", "inscription|비문, 새김글",
        "interlude|막간", "irony|아이러니", "kinetic art|동적 예술",
        "libretto|리브레토", "literary|문학적인", "lithograph|석판화",
        "manuscript|원고", "marquee|큰 천막", "memoir|회고록",
        "metaphor|은유", "minimalism|미니멀리즘", "montage|몽타주",
        "mosaic|모자이크", "motif|모티프", "mythology|신화학",
        "naturalism|자연주의", "neoclassical|신고전주의의", "notation|표기법",
        "ode|송시", "oratorio|오라토리오", "ornament|장식물",
        "overture|서곡", "pantomime|무언극", "parable|비유, 우화",
        "parody|패러디", "pastel|파스텔", "pathos|비애",
        "pavilion|정자, 전시관", "percussion|타악기", "perspective|원근법",
        "playwright|극작가", "polyphony|다성음악", "postmodernism|포스트모더니즘",
        "prelude|전주곡", "propaganda art|선전 예술", "protagonist|주인공",
        "realism|사실주의", "recital|독주회", "renaissance|르네상스",
        "repertoire|레퍼토리", "rhetoric|수사학", "romanticism|낭만주의",
        "sarcasm|비꼼, 풍자", "screenplay|시나리오", "silhouette|실루엣",
        "simile|직유, 비유", "sonata|소나타", "sonnet|소네트",
        "stanza|연, 시절", "still life|정물화", "stucco|치장벽토",
        "subtext|숨은 의미", "surrealism|초현실주의", "tableau|화면, 장면",
        "tapestry|태피스트리", "tempera|템페라", "terracotta|테라코타",
        "thematic|주제의", "triptych|세폭제단화", "troubadour|음유시인",
        "typography|타이포그래피", "utopia|유토피아", "vaudeville|보드빌",
        "vernacular|토착어", "virtuoso|거장", "vignette|짧은 이야기",
        "watercolor|수채화", "whimsical|기발한", "woodcut|목판화",
        "abstract art|추상 미술", "acappella|아카펠라", "acoustic|음향의",
        "aestheticism|유미주의", "allegretto|알레그레토", "aria|아리아",
        "artisan|장인", "burlesque|풍자극", "canto|시가의 편",
        "ceramist|도예가", "chancel|내진", "classicism|고전주의",
        "coda|코다", "concerto|협주곡", "counterpoint|대위법",
        "diorama|디오라마", "eclectic|절충적인", "epilogue|에필로그",
        "etude|연습곡", "fandango|판당고", "filigree|금은세공",
        "forte|포르테, 장기", "gargoyle|가고일", "genre painting|풍속화",
        "glyph|부조, 문양", "gothic|고딕의", "griot|서아프리카 음유시인",
    ],
    education: [
        "accreditation|인가, 인증", "aptitude|적성, 소질", "audit|청강하다",
        "bilingual|이중언어의", "bursary|장학금", "colloquium|학술토론회",
        "competency|역량, 능력", "cram|벼락공부하다", "criterion|기준",
        "dean|학장", "didactic|교훈적인", "dissertation|학위논문",
        "doctorate|박사학위", "dormitory|기숙사", "elective|선택과목",
        "empirical|경험적인, 실증적인", "endowment|기금", "extracurricular|교과외의",
        "faculty|교수진", "fellowship|연구장학금", "formative|형성적인",
        "holistic|전인적인", "honors|우등", "illiteracy|문맹",
        "immersion|몰입", "interdisciplinary|학제간의", "internship|인턴십",
        "magna cum laude|우등으로", "methodology|방법론", "module|모듈, 과정단위",
        "montessori|몬테소리", "pedagogy|교수법", "peer review|동료 평가",
        "plagiarism|표절", "postgraduate|대학원의", "prerequisite|선수과목",
        "proctor|시험감독관", "proficiency|능숙, 숙달", "provost|학무처장",
        "remedial|보충의", "retention|유지율", "rubric|평가기준표",
        "sabbatical|안식년", "standardized test|표준화 시험", "summa cum laude|최우등으로",
        "symposium|학술대회", "tenure|종신재직권", "transcript|성적증명서",
        "undergraduate|학부의", "valedictorian|수석졸업자", "vocational|직업의",
        "accredit|인정하다", "adjunct|겸임의", "alma mater|모교",
        "annotate|주석을 달다", "articulate|명확히 표현하다", "assessor|평가자",
        "benchmark|기준점", "caliber|수준, 자질", "charter school|특수목적학교",
        "citation|인용", "cognitive|인지적인", "commencement|학위수여식",
        "compulsory|의무적인", "convocation|소집, 학위수여식", "core curriculum|핵심교육과정",
        "correspondence course|통신교육", "credentialing|자격인증", "cum laude|우등으로",
        "deferment|연기, 유예", "delineate|기술하다", "differentiated|차등화된",
        "diploma mill|학위남발기관", "discourse|담론", "doctoral|박사의",
        "edification|교화", "elucidate|분명히 하다", "endow|기부하다",
        "epistemology|인식론", "erudite|박식한", "exemplary|모범적인",
        "expository|설명적인", "extramural|교외의", "formulate|공식화하다",
        "foundational|기초적인", "heuristic|발견적인", "inculcate|주입하다",
        "inductive|귀납적인", "inference|추론", "intellectual|지적인",
        "iterative|반복적인", "jurisprudence|법학", "kinesthetic|운동감각의",
        "lab practicum|실습", "longitudinal|종단적인", "metacognition|메타인지",
        "normative|규범적인", "objective|목표, 객관적인", "ontology|존재론",
        "paradigm|패러다임", "pedagogue|교사", "philology|문헌학",
        "postdoctoral|박사후의", "praxis|실천", "precept|교훈",
        "primer|입문서", "probation|수습", "propositional|명제적인",
        "qualitative|질적인", "quantitative|양적인", "rationale|근거, 이유",
        "recapitulate|요약하다", "reductionism|환원주의", "requisite|필수의",
        "rigor|엄격함", "scaffolding|비계, 교수지원", "scholarly|학술적인",
        "semiotics|기호학", "socratic|소크라테스식의", "specialize|전문화하다",
        "stipend|장학금, 수당", "subjective|주관적인", "summative|총괄적인",
        "taxonomy|분류학", "tuition|등록금", "tutorial|개별지도",
        "utilitarian|실용주의의", "vernacular|토착어", "webinar|웹 세미나",
        "apprentice|도제, 견습생", "audit trail|감사 추적", "brainstorm|브레인스토밍하다",
        "case study|사례 연구", "cohort|동기, 집단", "curriculum vitae|이력서",
    ],
    health: [
        "acupuncture|침술", "adrenaline|아드레날린", "ailment|질환",
        "amnesia|기억상실증", "anemia|빈혈", "anesthesia|마취",
        "artery|동맥", "asthma|천식", "autopsy|부검",
        "benign|양성의", "biopsy|생체검사", "bronchitis|기관지염",
        "cardiology|심장학", "cataract|백내장", "cholesterol|콜레스테롤",
        "circulatory|순환의", "clinical trial|임상시험", "cognitive therapy|인지치료",
        "collagen|콜라겐", "contraception|피임", "convulsion|경련",
        "cortisol|코르티솔", "dehydration|탈수", "dementia|치매",
        "dermatology|피부과학", "dialysis|투석", "dosage|용량",
        "dyslexia|난독증", "edema|부종", "electrocardiogram|심전도",
        "endocrine|내분비의", "epidemiology|역학", "epilepsy|간질",
        "gastric|위의", "genetic disorder|유전질환", "geriatric|노인의학의",
        "glucose|포도당", "hallucination|환각", "hematology|혈액학",
        "hepatitis|간염", "holistic medicine|전인의학", "homeostasis|항상성",
        "immunology|면역학", "incision|절개", "insomnia|불면증",
        "intravenous|정맥주사의", "lesion|병변", "ligament|인대",
        "malaria|말라리아", "mammography|유방촬영술", "meningitis|수막염",
        "metabolism|물질대사", "midwifery|조산술", "morphine|모르핀",
        "neurology|신경학", "neurotransmitter|신경전달물질", "obstetrics|산과학",
        "oncology|종양학", "ophthalmology|안과학", "orthopedic|정형외과의",
        "osteoporosis|골다공증", "outpatient|외래환자", "pacemaker|심박조율기",
        "pandemic|팬데믹, 세계적 유행병", "pathology|병리학", "pediatric|소아과의",
        "penicillin|페니실린", "pharmaceutical|제약의", "physical therapy|물리치료",
        "placebo|위약", "pneumonia|폐렴", "prognosis|예후",
        "prosthesis|보철물", "psychiatry|정신과학", "quarantine|격리",
        "radiology|방사선학", "remission|완화, 차도", "renal|신장의",
        "respiration|호흡", "resuscitate|소생시키다", "rheumatism|류머티즘",
        "sedative|진정제", "sepsis|패혈증", "serum|혈청",
        "sinus|부비강", "somatic|신체의", "spleen|비장",
        "sterilize|살균하다", "stethoscope|청진기", "strep|연쇄상구균",
        "subcutaneous|피하의", "tendon|힘줄", "tonsil|편도선",
        "topical|국소의", "trauma|외상, 트라우마", "triage|환자분류",
        "tuberculosis|결핵", "ultrasound|초음파", "urologist|비뇨기과의사",
        "vascular|혈관의", "vein|정맥", "ventilator|인공호흡기",
        "vertigo|현기증", "virology|바이러스학", "withdrawal|금단",
        "abscess|농양", "acetaminophen|아세트아미노펜", "adrenal gland|부신",
        "angioplasty|혈관성형술", "arthritis|관절염", "atrophy|위축",
        "benzodiazepine|벤조디아제핀", "bioethics|생명윤리", "blister|물집",
        "bypass surgery|우회술", "carcinogen|발암물질", "catheter|카테터",
        "cerebral|뇨의", "clot|혈전", "cochlear|달팽이관의",
        "concussion|뇌진탕", "CPR|심폐소생술", "cyst|낭종",
        "dialysis|투석", "diaphragm|횡격막", "EEG|뇌파검사",
        "embolism|색전증", "endoscopy|내시경검사", "femur|대퇴골",
        "gangrene|괴저", "hemoglobin|헤모글로빈", "hernia|탈장",
        "hypertension|고혈압", "hypothermia|저체온증", "immune system|면역체계",
        "inoculate|예방접종하다", "insulin|인슐린", "jaundice|황달",
        "larynx|후두", "malignant|악성의", "MRI|자기공명영상",
        "narcotic|마약성 진통제", "neonatal|신생아의", "opioid|오피오이드",
        "palliate|완화하다", "platelet|혈소판", "polyp|폴립, 용종",
    ],
    global: [
        "accession|가입, 취임", "annex|합병하다", "apartheid|인종격리",
        "appeasement|유화정책", "arbitration|중재", "armistice|휴전",
        "autarky|경제적 자급자족", "belligerent|교전국의", "bloc|블록, 진영",
        "buffer state|완충국", "cede|할양하다", "charter|헌장",
        "clout|영향력", "coexistence|공존", "Cold War|냉전",
        "colonize|식민지화하다", "conscription|징병제", "containment|봉쇄정책",
        "counterinsurgency|대반란작전", "de facto|사실상의", "de jure|법적인",
        "demarcation|경계, 구획", "demilitarize|비무장화하다", "deploy|배치하다",
        "detente|데탕트, 긴장완화", "deterrence|억제력", "devolution|권한이양",
        "dispatch|급파하다", "doctrine|독트린", "dominion|자치령",
        "enact|법률로 제정하다", "envoy|특사", "espionage|첩보활동",
        "ethnic cleansing|인종 청소", "extradite|인도하다", "garrison|수비대",
        "geopolitics|지정학", "guerrilla|게릴라", "hegemonic|패권적인",
        "humanitarian law|인도주의법", "incursion|침입", "insurgent|반란군",
        "isolationism|고립주의", "junta|군사정권", "mandate|위임통치",
        "martial|군사의", "mediate|중재하다", "mercenary|용병",
        "mobilize|동원하다", "moratorium|유예, 일시정지", "multilateral|다자간의",
        "neutrality|중립", "nonaligned|비동맹의", "nonproliferation|비확산",
        "pacifism|평화주의", "pact|조약, 협정", "partisan warfare|빨치산전",
        "peacekeeping|평화유지", "preemptive|선제적인", "proliferate|확산하다",
        "rapprochement|화해, 관계개선", "ratify|비준하다", "realpolitik|현실정치",
        "reconnaissance|정찰", "reparations|배상금", "repatriation|본국송환",
        "reprisal|보복", "revanchism|보복주의", "sabotage|사보타주, 방해공작",
        "secede|분리독립하다", "self-determination|자결권", "siege|포위",
        "sovereignty|주권", "sphere of influence|세력권", "stalemate|교착상태",
        "stratagem|전략, 계략", "subversive|체제전복적인", "suzerainty|종주권",
        "territorial|영토의", "theocracy|신정정치", "tribunal|재판소",
        "ultimatum|최후통첩", "unilateral|일방적인", "vassal|속국",
        "warlord|군벌", "zealotry|광신", "annihilate|전멸시키다",
        "attrition|소모전", "capitulate|항복하다", "cessation|중지",
        "civic engagement|시민참여", "clandestine|비밀의", "consortium|컨소시엄",
        "custodian|관리인", "demobilize|제대시키다", "dignitary|고관",
        "emissary|밀사", "enclave|거류지", "entente|협약",
        "exodus|대량이주", "extraterritorial|치외법권적", "fait accompli|기정사실",
        "fratricide|동포상잔", "accord|합의, 협정", "aggression|침략",
        "ambassador|대사", "asylum|망명", "blockade|봉쇄",
        "buffer zone|완충지대", "cease|중단하다", "civilian|민간인",
        "coerce|강요하다", "colonist|식민지 주민", "commemorate|기념하다",
        "confederate|연합한", "congress|의회, 회의", "convoy|호송대",
        "cosmopolitan|세계적인", "declaration|선언", "defect|망명하다, 탈주하다",
        "demography|인구학", "deportation|추방", "designate|지정하다",
        "displace|이동시키다", "drone strike|드론 공격", "encroach|침범하다",
        "fortify|요새화하다", "fugitive|도주자", "grieve|슬퍼하다",
        "ideology|사상", "imminent|임박한", "impasse|교착상태",
        "incumbent|현직의", "indigenous|원주민의", "instigate|선동하다",
        "legitimacy|정당성", "levy|부과하다", "martial law|계엄",
    ],
};
