// 고등 기초 단어 1000개 (8개 분야 × 125개) - 중등과 중복 없음
// Format: "word|의미|/발음/|동의어1,동의어2|반의어1,반의어2"
module.exports = {
    society: [
        "bureaucracy|관료제|/bjʊˈrɒkrəsi/|administration,red tape|",
        "advocate|옹호하다, 지지자|/ˈædvəkeɪt/|support,champion|oppose",
        "amendment|수정, 개정|/əˈmendmənt/|revision,change|",
        "ballot|투표, 투표용지|/ˈbælət/|vote,poll|",
        "bias|편향, 편견|/ˈbaɪəs/|prejudice,partiality|objectivity",
        "censor|검열하다|/ˈsensər/|suppress,restrict|permit",
        "civic|시민의|/ˈsɪvɪk/|public,municipal|private",
        "conform|순응하다|/kənˈfɔːrm/|comply,follow|rebel",
        "conservative|보수적인|/kənˈsɜːrvətɪv/|traditional,cautious|liberal",
        "constituent|유권자, 구성원|/kənˈstɪtʃuənt/|voter,member|",
        "controversial|논란이 많은|/ˌkɒntrəˈvɜːrʃl/|debatable,disputed|uncontested",
        "deliberate|신중한, 의도적인|/dɪˈlɪbərət/|intentional,planned|accidental",
        "demographic|인구통계학적|/ˌdeməˈɡræfɪk/|population-related|",
        "disparity|불균형, 격차|/dɪˈspærəti/|inequality,gap|equality",
        "doctrine|교리, 원칙|/ˈdɒktrɪn/|belief,principle|",
        "domestic|국내의, 가정의|/dəˈmestɪk/|internal,home|foreign",
        "enforce|집행하다, 시행하다|/ɪnˈfɔːrs/|implement,impose|repeal",
        "exile|추방, 망명|/ˈeksaɪl/|banishment,deportation|return",
        "faction|파벌, 분파|/ˈfækʃn/|group,clique|unity",
        "governance|통치|/ˈɡʌvərnəns/|rule,administration|anarchy",
        "grassroots|풀뿌리의|/ˈɡræsruːts/|local,bottom-up|top-down",
        "grievance|불만, 고충|/ˈɡriːvəns/|complaint,objection|satisfaction",
        "hierarchy|계층, 서열|/ˈhaɪərɑːrki/|ranking,order|equality",
        "ideology|이데올로기|/ˌaɪdiˈɒlədʒi/|belief system,doctrine|",
        "impartial|공정한|/ɪmˈpɑːrʃl/|unbiased,neutral|biased",
        "incumbent|현직의|/ɪnˈkʌmbənt/|current,sitting|challenger",
        "inequity|불공평|/ɪnˈekwɪti/|unfairness,injustice|equity",
        "jurisdiction|관할권|/ˌdʒʊrɪsˈdɪkʃn/|authority,domain|",
        "legislature|입법부|/ˈledʒɪsleɪtʃər/|congress,parliament|",
        "liberal|자유주의의|/ˈlɪbərəl/|progressive,open-minded|conservative",
        "lobby|로비하다|/ˈlɒbi/|campaign,persuade|",
        "mandate|명령, 위임|/ˈmændeɪt/|order,decree|request",
        "marginalize|소외시키다|/ˈmɑːrdʒɪnəlaɪz/|exclude,ignore|include",
        "mediator|중재자|/ˈmiːdieɪtər/|negotiator,arbitrator|",
        "milestone|이정표|/ˈmaɪlstoʊn/|landmark,achievement|setback",
        "municipal|시의, 도시의|/mjuːˈnɪsɪpl/|city,local|national",
        "oath|맹세, 서약|/oʊθ/|pledge,vow|",
        "oppressed|억압받는|/əˈprest/|downtrodden,subjugated|liberated",
        "ordinance|조례|/ˈɔːrdɪnəns/|law,decree|",
        "partisan|당파적인|/ˈpɑːrtɪzn/|biased,factional|neutral",
        "petition|청원서|/pəˈtɪʃn/|appeal,request|",
        "pluralism|다원주의|/ˈplʊrəlɪzm/|diversity,variety|uniformity",
        "populism|대중주의|/ˈpɒpjulɪzm/|people's movement|elitism",
        "precedent|선례|/ˈpresɪdənt/|example,model|exception",
        "progressive|진보적인|/prəˈɡresɪv/|liberal,forward-thinking|conservative",
        "prosecute|기소하다|/ˈprɒsɪkjuːt/|charge,indict|defend",
        "provoke|자극하다, 도발하다|/prəˈvoʊk/|incite,irritate|calm",
        "radical|급진적인|/ˈrædɪkl/|extreme,revolutionary|moderate",
        "ratify|비준하다|/ˈrætɪfaɪ/|approve,confirm|reject",
        "referendum|국민투표|/ˌrefəˈrendəm/|public vote,plebiscite|",
        "regime|체제, 정권|/reɪˈʒiːm/|government,system|",
        "rehabilitate|사회 복귀시키다|/ˌriːhəˈbɪlɪteɪt/|restore,reform|",
        "repeal|폐지하다|/rɪˈpiːl/|revoke,cancel|enact",
        "segregation|분리, 차별|/ˌseɡrɪˈɡeɪʃn/|separation,isolation|integration",
        "sovereignty|주권|/ˈsɒvrɪnti/|supremacy,independence|subjugation",
        "statute|법규, 법령|/ˈstætʃuːt/|law,regulation|",
        "stigma|낙인|/ˈstɪɡmə/|shame,mark|honor",
        "subculture|하위 문화|/ˈsʌbkʌltʃər/|niche culture|mainstream",
        "subordinate|부하의, 종속적인|/səˈbɔːrdɪnət/|inferior,secondary|superior",
        "subsidy|보조금|/ˈsʌbsɪdi/|grant,aid|tax",
        "suppress|억압하다|/səˈpres/|restrain,silence|express",
        "surveillance|감시|/sərˈveɪləns/|monitoring,observation|privacy",
        "testimony|증언|/ˈtestɪmoʊni/|evidence,statement|",
        "tribunal|재판소|/traɪˈbjuːnl/|court,panel|",
        "uphold|지지하다|/ʌpˈhoʊld/|maintain,support|reject",
        "verdict|판결|/ˈvɜːrdɪkt/|judgment,ruling|",
        "violation|위반|/ˌvaɪəˈleɪʃn/|breach,offense|compliance",
        "warrant|영장|/ˈwɒrənt/|authorization,permit|",
        "asylum seeker|망명 신청자|/əˈsaɪləm ˈsiːkər/|refugee|",
        "autocracy|독재정치|/ɔːˈtɒkrəsi/|dictatorship|democracy",
        "benevolent|자비로운|/bəˈnevələnt/|kind,charitable|malevolent",
        "boycott|보이콧, 불매 운동|/ˈbɔɪkɒt/|ban,embargo|support",
        "bureaucratic|관료적인|/ˌbjʊrəˈkrætɪk/|administrative|efficient",
        "coerce|강요하다|/koʊˈɜːrs/|force,compel|persuade",
        "compatriot|동포|/kəmˈpætriət/|countryman,fellow citizen|foreigner",
        "consent|동의|/kənˈsent/|agreement,permission|refusal",
        "decree|법령|/dɪˈkriː/|order,edict|",
        "defiance|반항|/dɪˈfaɪəns/|resistance,rebellion|compliance",
        "despotism|전제 정치|/ˈdespətɪzm/|tyranny,authoritarianism|democracy",
        "dissident|반체제 인사|/ˈdɪsɪdənt/|rebel,protester|conformist",
        "egalitarian|평등주의의|/ɪˌɡælɪˈteriən/|equal,democratic|elitist",
        "emancipation|해방|/ɪˌmænsɪˈpeɪʃn/|liberation,freedom|enslavement",
        "espionage|간첩 행위|/ˈespiənɑːʒ/|spying,intelligence|",
        "exile|추방하다|/ˈeksaɪl/|banish,deport|welcome",
        "feminism|여성주의|/ˈfemɪnɪzm/|women's rights|",
        "franchise|투표권, 가맹점|/ˈfræntʃaɪz/|right to vote|",
        "hegemony|패권|/hɪˈdʒeməni/|dominance,supremacy|subordination",
        "humanitarian aid|인도적 지원|/hjuːˌmænɪˈteriən eɪd/|relief,assistance|",
        "inaugural|취임의|/ɪˈnɔːɡjərəl/|opening,first|final",
        "insurrection|반란|/ˌɪnsəˈrekʃn/|revolt,uprising|peace",
        "jurisprudence|법학|/ˌdʒʊrɪsˈpruːdns/|legal science|",
        "legitimate|합법적인|/lɪˈdʒɪtɪmət/|lawful,valid|illegitimate",
        "martial law|계엄령|/ˈmɑːrʃl lɔː/|military rule|civilian rule",
        "meritocracy|능력주의|/ˌmerɪˈtɒkrəsi/|merit system|nepotism",
        "oligarchy|과두제|/ˈɒlɪɡɑːrki/|elite rule|democracy",
        "ombudsman|옴부즈만, 감찰관|/ˈɒmbʌdzmən/|investigator,watchdog|",
        "plebiscite|국민투표|/ˈplebɪsaɪt/|referendum,vote|",
        "pragmatic|실용적인|/præɡˈmætɪk/|practical,realistic|idealistic",
        "preamble|전문, 서문|/ˈpriːæmbl/|introduction,preface|conclusion",
        "propaganda|선전|/ˌprɒpəˈɡændə/|campaign,publicity|truth",
        "quorum|정족수|/ˈkwɔːrəm/|minimum number|",
        "ratification|비준|/ˌrætɪfɪˈkeɪʃn/|approval,endorsement|rejection",
        "recount|재검표|/ˈriːkaʊnt/|recheck,review|",
        "reparation|배상|/ˌrepəˈreɪʃn/|compensation,amends|",
        "secession|탈퇴, 분리|/sɪˈseʃn/|withdrawal,separation|union",
        "suffrage|참정권|/ˈsʌfrɪdʒ/|right to vote|disenfranchisement",
        "totalitarian|전체주의의|/toʊˌtælɪˈteriən/|authoritarian,dictatorial|democratic",
        "transparency|투명성|/trænsˈpærənsi/|openness,clarity|opacity",
        "tyranny|폭정|/ˈtɪrəni/|despotism,oppression|freedom",
        "unanimous|만장일치의|/juˈnænɪməs/|agreed,united|divided",
        "unrest|불안, 소요|/ʌnˈrest/|turmoil,disturbance|peace",
        "vanguard|선봉|/ˈvænɡɑːrd/|forefront,leaders|rear",
        "whistleblower|내부 고발자|/ˈwɪslbloʊər/|informant|",
        "xenophobia|외국인 혐오|/ˌzenəˈfoʊbiə/|racism,intolerance|tolerance",
        "zealot|열광자|/ˈzelət/|fanatic,extremist|moderate",
        "abolitionist|폐지론자|/ˌæbəˈlɪʃənɪst/|reformer|",
        "amnesty|사면|/ˈæmnəsti/|pardon,forgiveness|punishment",
        "anarchist|무정부주의자|/ˈænərkɪst/|rebel|conformist",
        "aristocracy|귀족 정치|/ˌærɪˈstɒkrəsi/|nobility,elite|common people",
        "capitalism|자본주의|/ˈkæpɪtəlɪzm/|free enterprise|socialism",
        "censorship|검열|/ˈsensərʃɪp/|suppression,control|freedom",
        "collectivism|집단주의|/kəˈlektɪvɪzm/|communalism|individualism",
        "demagogue|선동가|/ˈdeməɡɒɡ/|agitator,rabble-rouser|statesman",
        "diaspora|이산|/daɪˈæspərə/|dispersion,scattering|homeland",
    ],
    economy: [
        "acquisition|인수, 취득|/ˌækwɪˈzɪʃn/|purchase,obtainment|disposal",
        "aggregate|합계, 총합|/ˈæɡrɪɡət/|total,sum|individual",
        "allocate|배분하다|/ˈæləkeɪt/|assign,distribute|withhold",
        "amortize|분할 상환하다|/ˈæmərtaɪz/|pay off,redeem|",
        "appreciate|가치가 오르다|/əˈpriːʃieɪt/|increase,rise|depreciate",
        "arbitrage|차익 거래|/ˈɑːrbɪtrɑːʒ/|trading,speculation|",
        "austerity|긴축|/ɔːˈsterəti/|frugality,restraint|spending",
        "bailout|구제 금융|/ˈbeɪlaʊt/|rescue,relief|",
        "benchmark|기준점|/ˈbentʃmɑːrk/|standard,reference|",
        "boom|호황|/buːm/|prosperity,growth|bust",
        "brokerage|중개업|/ˈbroʊkərɪdʒ/|agency,trading|",
        "buyout|기업 매수|/ˈbaɪaʊt/|acquisition,takeover|",
        "cartel|카르텔|/kɑːrˈtel/|monopoly,syndicate|competition",
        "collateral|담보|/kəˈlætərəl/|security,guarantee|",
        "commodity exchange|상품 거래소|/kəˈmɒdəti ɪksˈtʃeɪndʒ/|market|",
        "conglomerate|대기업|/kənˈɡlɒmərət/|corporation,group|",
        "consolidate|통합하다|/kənˈsɒlɪdeɪt/|merge,unite|divide",
        "creditor|채권자|/ˈkredɪtər/|lender|debtor",
        "deflation|디플레이션|/diːˈfleɪʃn/|price drop|inflation",
        "depreciate|가치가 하락하다|/dɪˈpriːʃieɪt/|decrease,decline|appreciate",
        "deregulation|규제 완화|/diːˌreɡjuˈleɪʃn/|liberalization|regulation",
        "diversify|다각화하다|/daɪˈvɜːrsɪfaɪ/|vary,expand|specialize",
        "dividend|배당금|/ˈdɪvɪdend/|payout,share|",
        "downturn|경기 침체|/ˈdaʊntɜːrn/|decline,recession|upturn",
        "e-commerce|전자상거래|/ˈiː kɒmɜːrs/|online shopping|",
        "embargo|통상 금지|/ɪmˈbɑːrɡoʊ/|ban,blockade|free trade",
        "endowment|기부금, 기금|/ɪnˈdaʊmənt/|fund,grant|",
        "equity|자기자본|/ˈekwɪti/|ownership,stake|debt",
        "expenditure|지출|/ɪkˈspendɪtʃər/|spending,cost|income",
        "fiscal|재정의|/ˈfɪskl/|financial,monetary|",
        "fluctuate|변동하다|/ˈflʌktʃueɪt/|vary,oscillate|stabilize",
        "franchise|프랜차이즈|/ˈfræntʃaɪz/|license,chain|",
        "freelance|프리랜서의|/ˈfriːlæns/|independent,self-employed|employed",
        "GDP|국내총생산|/ˌdʒiː diː ˈpiː/|gross domestic product|",
        "globalize|세계화하다|/ˈɡloʊbəlaɪz/|internationalize|localize",
        "hedge|위험을 회피하다|/hedʒ/|protect,safeguard|expose",
        "hyperinflation|초인플레이션|/ˌhaɪpərɪnˈfleɪʃn/|extreme inflation|deflation",
        "incentive|인센티브, 장려금|/ɪnˈsentɪv/|motivation,reward|disincentive",
        "index|지수|/ˈɪndeks/|indicator,measure|",
        "infrastructure|하부구조, 인프라|/ˈɪnfrəstrʌktʃər/|framework,foundation|",
        "insolvency|지급 불능|/ɪnˈsɒlvənsi/|bankruptcy|solvency",
        "leverage|레버리지, 지렛대|/ˈlevərɪdʒ/|influence,advantage|disadvantage",
        "liability|부채, 책임|/ˌlaɪəˈbɪləti/|obligation,debt|asset",
        "liquidate|청산하다|/ˈlɪkwɪdeɪt/|sell off,dissolve|acquire",
        "liquidity|유동성|/lɪˈkwɪdəti/|cash flow|illiquidity",
        "macroeconomics|거시경제학|/ˌmækroʊˌiːkəˈnɒmɪks/|broad economics|microeconomics",
        "merger|합병|/ˈmɜːrdʒər/|combination,union|split",
        "microeconomics|미시경제학|/ˌmaɪkroʊˌiːkəˈnɒmɪks/|individual economics|macroeconomics",
        "monetary|금전적인, 통화의|/ˈmʌnɪteri/|financial,fiscal|",
        "monopoly|독점|/məˈnɒpəli/|exclusive control|competition",
        "mortgage|주택 담보 대출|/ˈmɔːrɡɪdʒ/|home loan|",
        "outsource|외주를 맡기다|/ˈaʊtsɔːrs/|delegate,contract out|insource",
        "overhead|간접비|/ˈoʊvərhed/|fixed costs,expenses|",
        "pension|연금|/ˈpenʃn/|retirement fund|",
        "portfolio|포트폴리오|/pɔːrtˈfoʊlioʊ/|collection,holdings|",
        "privatize|민영화하다|/ˈpraɪvətaɪz/|denationalize|nationalize",
        "procurement|조달|/prəˈkjʊrmənt/|purchase,acquisition|",
        "quota|할당량|/ˈkwoʊtə/|limit,share|",
        "recession|불경기|/rɪˈseʃn/|downturn,slump|boom",
        "remittance|송금|/rɪˈmɪtns/|transfer,payment|",
        "restructure|구조 조정하다|/riːˈstrʌktʃər/|reorganize,reform|",
        "securities|유가증권|/sɪˈkjʊrətiz/|stocks,bonds|",
        "shareholder|주주|/ˈʃerhoʊldər/|stockholder,investor|",
        "solvent|지급 능력이 있는|/ˈsɒlvənt/|financially stable|insolvent",
        "speculation|투기|/ˌspekjuˈleɪʃn/|gamble,risk|certainty",
        "stagnation|정체|/stæɡˈneɪʃn/|standstill,inactivity|growth",
        "stakeholder|이해관계자|/ˈsteɪkhoʊldər/|interested party|",
        "startup|스타트업|/ˈstɑːrtʌp/|new business,venture|corporation",
        "subsistence|생존, 생계|/səbˈsɪstəns/|survival,livelihood|prosperity",
        "surplus|잉여, 흑자|/ˈsɜːrpləs/|excess,extra|deficit",
        "syndicate|신디케이트|/ˈsɪndɪkət/|consortium,group|",
        "tariff|관세|/ˈtærɪf/|duty,tax|free trade",
        "tender|입찰|/ˈtendər/|bid,offer|",
        "turnover|매출액, 이직률|/ˈtɜːrnoʊvər/|revenue,rotation|",
        "underwrite|인수하다|/ˌʌndərˈraɪt/|guarantee,insure|",
        "utility|공익 사업|/juːˈtɪləti/|service,usefulness|",
        "valuation|가치 평가|/ˌvæljuˈeɪʃn/|appraisal,assessment|",
        "venture capital|벤처 자본|/ˈventʃər ˈkæpɪtl/|risk investment|",
        "volatility|변동성|/ˌvɒləˈtɪləti/|instability,fluctuation|stability",
        "windfall|횡재|/ˈwɪndfɔːl/|bonanza,jackpot|loss",
        "yield curve|수익률 곡선|/jiːld kɜːrv/|interest rate graph|",
        "blue chip|우량주|/bluː tʃɪp/|premium stock|penny stock",
        "bond|채권|/bɒnd/|security,debenture|",
        "bottom line|수익, 결론|/ˈbɒtəm laɪn/|profit,outcome|",
        "breakeven|손익분기점|/ˈbreɪkiːvn/|balance point|",
        "bull market|강세장|/bʊl ˈmɑːrkɪt/|rising market|bear market",
        "bear market|약세장|/ber ˈmɑːrkɪt/|falling market|bull market",
        "barter|물물교환|/ˈbɑːrtər/|trade,swap|purchase",
        "capita|1인당|/ˈkæpɪtə/|per person|",
        "commodity|원자재|/kəˈmɒdəti/|raw material|finished product",
        "compliance|준수|/kəmˈplaɪəns/|adherence,conformity|violation",
        "consortium|컨소시엄|/kənˈsɔːrtiəm/|alliance,partnership|",
        "default|채무불이행|/dɪˈfɔːlt/|failure to pay|fulfillment",
        "devaluation|평가절하|/diːˌvæljuˈeɪʃn/|depreciation|revaluation",
        "fiduciary|신탁의|/fɪˈdjuːʃieri/|trustee,custodial|",
        "float|변동 환율제|/floʊt/|fluctuate|peg",
        "foreclosure|압류|/fɔːrˈkloʊʒər/|seizure,repossession|",
        "gross|총, 총액|/ɡroʊs/|total,overall|net",
        "installment|할부금|/ɪnˈstɔːlmənt/|payment,portion|lump sum",
        "insure|보험에 가입하다|/ɪnˈʃʊr/|protect,cover|",
        "inventory turnover|재고 회전율|/ˈɪnvəntɔːri ˈtɜːrnoʊvər/|stock rotation|",
        "IPO|기업공개|/ˌaɪ piː ˈoʊ/|initial public offering|",
        "lease|리스, 임대계약|/liːs/|rental agreement|purchase",
        "markup|마진, 인상분|/ˈmɑːrkʌp/|price increase|markdown",
        "net|순, 실질적인|/net/|after deductions|gross",
        "oligopoly|과점|/ˌɒlɪˈɡɒpəli/|limited competition|perfect competition",
        "piggyback|편승하다|/ˈpɪɡibæk/|ride along|",
        "receivable|미수금|/rɪˈsiːvəbl/|owed amount|payable",
        "reimbursement|상환, 배상|/ˌriːɪmˈbɜːrsmənt/|refund,repayment|",
        "royalty|로열티, 인세|/ˈrɔɪəlti/|fee,commission|",
        "subsidy|지원금|/ˈsʌbsɪdi/|grant,funding|tax",
        "tycoon|거물|/taɪˈkuːn/|magnate,mogul|",
        "undercut|원가 이하로 팔다|/ˌʌndərˈkʌt/|undersell|overprice",
        "usury|고리대금|/ˈjuːʒəri/|loan sharking|",
        "wholesale price|도매가|/ˈhoʊlseɪl praɪs/|bulk price|retail price",
        "write-off|상각|/ˈraɪt ɒf/|deduction,loss|",
    ],
    nature: [
        "abyss|심연|/əˈbɪs/|chasm,depth|surface",
        "adapt|적응하다|/əˈdæpt/|adjust,acclimate|resist",
        "algae|조류, 해조류|/ˈældʒiː/|seaweed,plankton|",
        "aquifer|대수층|/ˈækwɪfər/|underground water|",
        "arid|건조한|/ˈærɪd/|dry,parched|humid",
        "barren|불모의|/ˈbærən/|infertile,desolate|fertile",
        "basin|분지|/ˈbeɪsn/|bowl,depression|peak",
        "biodegradable|생분해성의|/ˌbaɪoʊdɪˈɡreɪdəbl/|decomposable|nonbiodegradable",
        "biome|생물 군계|/ˈbaɪoʊm/|ecosystem,habitat|",
        "canopy|수관층|/ˈkænəpi/|treetop cover|floor",
        "carnivore|육식 동물|/ˈkɑːrnɪvɔːr/|meat-eater|herbivore",
        "catalyst|촉매|/ˈkætəlɪst/|trigger,accelerator|inhibitor",
        "compost|퇴비|/ˈkɒmpoʊst/|fertilizer,mulch|",
        "condensation|응결|/ˌkɒndenˈseɪʃn/|water droplets|evaporation",
        "contaminate|오염시키다|/kənˈtæmɪneɪt/|pollute,poison|purify",
        "coral reef|산호초|/ˈkɒrəl riːf/|marine formation|",
        "crevice|갈라진 틈|/ˈkrevɪs/|crack,gap|",
        "decompose|분해하다|/ˌdiːkəmˈpoʊz/|decay,rot|preserve",
        "delta|삼각주|/ˈdeltə/|river mouth|",
        "deplete|고갈시키다|/dɪˈpliːt/|exhaust,drain|replenish",
        "drought resistant|가뭄에 강한|/draʊt rɪˈzɪstənt/|hardy|drought-sensitive",
        "ecology|생태학|/ɪˈkɒlədʒi/|environmental science|",
        "effluent|폐수|/ˈefluənt/|waste water,discharge|",
        "endangered species|멸종 위기 종|/ɪnˈdeɪndʒərd ˈspiːʃiːz/|threatened species|",
        "endemic|고유의|/enˈdemɪk/|native,indigenous|exotic",
        "erode|침식하다|/ɪˈroʊd/|wear away,deteriorate|build up",
        "estuary|하구|/ˈestʃueri/|river mouth,inlet|",
        "evaporate|증발하다|/ɪˈvæpəreɪt/|vaporize,dry up|condense",
        "extinct|멸종된|/ɪkˈstɪŋkt/|died out,vanished|extant",
        "fauna|동물상|/ˈfɔːnə/|animal life|flora",
        "flora|식물상|/ˈflɔːrə/|plant life|fauna",
        "foliage|잎|/ˈfoʊliɪdʒ/|leaves,greenery|",
        "fossil fuel|화석 연료|/ˈfɒsl fjuːəl/|coal,oil|renewable energy",
        "fungus|곰팡이, 균류|/ˈfʌŋɡəs/|mold,mushroom|",
        "geothermal|지열의|/ˌdʒiːoʊˈθɜːrml/|underground heat|",
        "germinate|발아하다|/ˈdʒɜːrmɪneɪt/|sprout,grow|wither",
        "groundwater|지하수|/ˈɡraʊndwɔːtər/|underground water|surface water",
        "herbivore|초식 동물|/ˈhɜːrbɪvɔːr/|plant-eater|carnivore",
        "horticulture|원예|/ˈhɔːrtɪkʌltʃər/|gardening,cultivation|",
        "humid|습한|/ˈhjuːmɪd/|moist,damp|dry",
        "hybrid|혼합종, 하이브리드|/ˈhaɪbrɪd/|crossbreed,mix|purebred",
        "indigenous|토착의|/ɪnˈdɪdʒɪnəs/|native,local|foreign",
        "irrigation|관개|/ˌɪrɪˈɡeɪʃn/|watering,sprinkling|drainage",
        "latitude|위도|/ˈlætɪtjuːd/|parallel|longitude",
        "longitude|경도|/ˈlɒndʒɪtjuːd/|meridian|latitude",
        "mangrove|맹그로브|/ˈmæŋɡroʊv/|coastal tree|",
        "marine biology|해양 생물학|/məˈriːn baɪˈɒlədʒi/|ocean science|",
        "meteorology|기상학|/ˌmiːtiəˈrɒlədʒi/|weather science|",
        "migration pattern|이동 패턴|/maɪˈɡreɪʃn ˈpætərn/|travel route|",
        "molten|녹은|/ˈmoʊltən/|melted,liquefied|solid",
        "monsoon|계절풍|/mɒnˈsuːn/|seasonal rain|drought",
        "nocturnal|야행성의|/nɒkˈtɜːrnl/|night-active|diurnal",
        "nutrient cycle|영양 순환|/ˈnjuːtriənt ˈsaɪkl/|food chain|",
        "omnivore|잡식 동물|/ˈɒmnɪvɔːr/|all-eater|",
        "organism|유기체|/ˈɔːrɡənɪzm/|living thing|",
        "ozone|오존|/ˈoʊzoʊn/|O3,atmosphere layer|",
        "parasite|기생충|/ˈpærəsaɪt/|leech,freeloader|host",
        "permafrost|영구 동토층|/ˈpɜːrməfrɒst/|frozen ground|",
        "pesticide|살충제|/ˈpestɪsaɪd/|insecticide,herbicide|",
        "photosynthesis|광합성|/ˌfoʊtoʊˈsɪnθəsɪs/|plant energy process|",
        "plankton|플랑크톤|/ˈplæŋktən/|microorganism|",
        "plateau|고원|/plæˈtoʊ/|tableland,highland|valley",
        "pollinate|수분하다|/ˈpɒlɪneɪt/|fertilize|",
        "precipitation|강수|/prɪˌsɪpɪˈteɪʃn/|rain,snow|evaporation",
        "primate|영장류|/ˈpraɪmeɪt/|ape,monkey|",
        "purify|정화하다|/ˈpjʊrɪfaɪ/|cleanse,filter|contaminate",
        "ravine|협곡|/rəˈviːn/|gorge,gully|plateau",
        "regenerate|재생하다|/rɪˈdʒenəreɪt/|renew,restore|destroy",
        "reservoir|저수지|/ˈrezərvwɑːr/|lake,tank|",
        "saline|염분이 있는|/ˈseɪliːn/|salty,brackish|fresh",
        "savanna|사바나|/səˈvænə/|grassland,plain|",
        "sediment|퇴적물|/ˈsedɪmənt/|deposit,silt|",
        "seismology|지진학|/saɪzˈmɒlədʒi/|earthquake science|",
        "stratosphere|성층권|/ˈstrætəsfɪr/|upper atmosphere|troposphere",
        "subspecies|아종|/ˈsʌbspiːʃiːz/|variety,race|",
        "symbiosis|공생|/ˌsɪmbaɪˈoʊsɪs/|mutualism,partnership|parasitism",
        "temperate|온대의|/ˈtempərət/|mild,moderate|extreme",
        "terrain|지형|/təˈreɪn/|landscape,ground|",
        "topography|지형학|/təˈpɒɡrəfi/|terrain study|",
        "toxic|유독한|/ˈtɒksɪk/|poisonous,harmful|nontoxic",
        "tributatry|지류|/ˈtrɪbjuteri/|branch river|main river",
        "tundra|툰드라|/ˈtʌndrə/|arctic plain|tropics",
        "understory|하층림|/ˈʌndərstɔːri/|forest floor|canopy",
        "vegetation zone|식생대|/ˌvedʒəˈteɪʃn zoʊn/|plant region|",
        "volcanic ash|화산재|/vɒlˈkænɪk æʃ/|tephra|",
        "watershed|분수령|/ˈwɔːtərʃed/|drainage basin|",
        "wetland conservation|습지 보전|/ˈwetlænd ˌkɒnsərˈveɪʃn/|marsh protection|",
        "wilderness|황야|/ˈwɪldərnəs/|wild area,untamed land|civilization",
        "zoology|동물학|/zuːˈɒlədʒi/|animal science|botany",
        "biosphere|생물권|/ˈbaɪoʊsfɪr/|living zone|",
        "chlorophyll|엽록소|/ˈklɔːrəfɪl/|green pigment|",
        "composting|퇴비화|/ˈkɒmpoʊstɪŋ/|organic recycling|",
        "conifer|침엽수|/ˈkɒnɪfər/|evergreen,pine|deciduous",
        "deciduous|낙엽성의|/dɪˈsɪdjuəs/|leaf-shedding|evergreen",
        "dune|사구, 모래 언덕|/djuːn/|sand hill|valley",
        "ecosystem services|생태계 서비스|/ˈiːkoʊsɪstəm ˈsɜːrvɪsɪz/|natural benefits|",
        "elevation|고도, 해발|/ˌelɪˈveɪʃn/|height,altitude|depth",
        "equator|적도|/ɪˈkweɪtər/|midline|pole",
        "fern|양치류|/fɜːrn/|frond plant|",
        "fjord|피오르|/fjɔːrd/|inlet,bay|",
        "food chain|먹이 사슬|/fuːd tʃeɪn/|food web|",
        "fossil record|화석 기록|/ˈfɒsl ˈrekɔːrd/|paleontological data|",
        "geyser|간헐천|/ˈɡaɪzər/|hot spring|",
        "habitat loss|서식지 손실|/ˈhæbɪtæt lɒs/|environment destruction|conservation",
        "hardwood|경목|/ˈhɑːrdwʊd/|tough timber|softwood",
        "lichen|이끼|/ˈlaɪkən/|moss,fungus|",
        "limestone|석회암|/ˈlaɪmstoʊn/|calcium rock|",
        "magma|마그마|/ˈmæɡmə/|molten rock|",
        "marsh|습지|/mɑːrʃ/|wetland,swamp|dryland",
        "migratory|이동하는|/ˈmaɪɡrətɔːri/|wandering,nomadic|sedentary",
        "moss|이끼|/mɒs/|bryophyte|",
        "natural selection|자연 선택|/ˈnætʃərəl sɪˈlekʃn/|survival of fittest|",
        "niche|생태적 지위|/niːʃ/|role,position|",
        "nitrogen|질소|/ˈnaɪtrədʒən/|N,element|",
        "phosphorus|인|/ˈfɒsfərəs/|P,element|",
        "photovoltaic|광전지의|/ˌfoʊtoʊvɒlˈteɪɪk/|solar powered|",
        "pollutant|오염 물질|/pəˈluːtənt/|contaminant|purifier",
        "quarry|채석장|/ˈkwɒri/|mine,pit|",
        "runoff|유출수|/ˈrʌnɒf/|drainage,overflow|absorption",
        "silt|미사, 퇴적물|/sɪlt/|sediment,mud|rock",
        "spore|포자|/spɔːr/|reproductive cell|seed",
        "thermal|열의|/ˈθɜːrml/|heat-related|cold",
        "topsoil|표토|/ˈtɒpsɔɪl/|surface soil|subsoil",
        "undergrowth|덤불|/ˈʌndərɡroʊθ/|bushes,shrubs|canopy",
    ],
    // Part 2 continues with remaining categories
    ...require('./words-high-p2.cjs'),
};
